package br.com.gc.modCelular.entity;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Geracoes generated by hbm2java
 */
@Entity
@Table(name = "geracoes", uniqueConstraints = @UniqueConstraint(columnNames = "gerDescricao"))
public class Geracoes implements java.io.Serializable {

	private static final long serialVersionUID = -1979223460134120472L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "gerCod", unique = true, nullable = false)
	private Integer gerCod;

	@Column(name = "gerDescricao", unique = true, nullable = false, length = 60)
	private String gerDescricao;

	public Integer getGerCod() {
		return this.gerCod;
	}

	public void setGerCod(Integer gerCod) {
		this.gerCod = gerCod;
	}

	public String getGerDescricao() {
		return this.gerDescricao;
	}

	public void setGerDescricao(String gerDescricao) {
		this.gerDescricao = gerDescricao;
	}

}
