package br.com.gc.modCelular.entity;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Igrejas generated by hbm2java
 */
@Entity
@Table(name = "igrejas")
public class Igrejas implements java.io.Serializable {

	private static final long serialVersionUID = -4064637046755344412L;
	
	@Id
	@Column(name = "idIgrejas")
	private Integer idIgrejas;

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "igrpaises", nullable = false)
//	private Paises paises;
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsavelMasculino", nullable = false)
	private Discipulos resposavelMasculino;
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "igrlogradouro", nullable = false)
	//private Logradouro logradouro;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsavelFeminino", nullable = false)
	private Discipulos responsavelFeminino;

	@Column(name = "nome", nullable = false, length = 100)
	private String nome;
	
	@Column(name = "logo", length = 100)
	private Byte[] logo;
	
	@Column(name = "diaVencimento")	
	private int diaVencimento;
	
	@Column(name = "status", length = 1)
	@Enumerated(EnumType.ORDINAL)
	private Status status;

	public Integer getIdIgrejas() {
		return idIgrejas;
	}

	public void setIdIgrejas(Integer idIgrejas) {
		this.idIgrejas = idIgrejas;
	}

	public Discipulos getResposavelMasculino() {
		return resposavelMasculino;
	}

	public void setResposavelMasculino(Discipulos resposavelMasculino) {
		this.resposavelMasculino = resposavelMasculino;
	}

	public Discipulos getResponsavelFeminino() {
		return responsavelFeminino;
	}

	public void setResponsavelFeminino(Discipulos responsavelFeminino) {
		this.responsavelFeminino = responsavelFeminino;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Byte[] getLogo() {
		return logo;
	}

	public void setLogo(Byte[] logo) {
		this.logo = logo;
	}

	public int getDiaVencimento() {
		return diaVencimento;
	}

	public void setDiaVencimento(int diaVencimento) {
		this.diaVencimento = diaVencimento;
	}

	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	
	
}
