package br.com.gc.modCelular.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estadocivil generated by hbm2java
 */
@Entity
@Table(name = "estadocivil", uniqueConstraints = @UniqueConstraint(columnNames = "Estdescricao"))
public class EstadoCivil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7720861098971185572L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EstCod", unique = true, nullable = false)
	private Integer estCod;

	@Column(name = "Estdescricao", unique = true, length = 60)
	private String estdescricao;

	public Integer getEstCod() {
		return this.estCod;
	}

	public void setEstCod(Integer estCod) {
		this.estCod = estCod;
	}

	public String getEstdescricao() {
		return this.estdescricao;
	}

	public void setEstdescricao(String estdescricao) {
		this.estdescricao = estdescricao;
	}

}
