package br.com.gc.modCelular.entity;

// Generated 11/05/2011 14:16:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Funcaoeclesiasticas generated by hbm2java
 */
@Entity
@Table(name = "funcaoeclesiasticas", uniqueConstraints = @UniqueConstraint(columnNames = {
		"funDescricao", "funSexo" }))
public class FuncaoEclesiasticas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6325030593032627427L;

	@Id
	@Column(name = "funCod", unique = true, nullable = false)
	private int funCod;

	@Column(name = "funDescricao", nullable = false, length = 60)
	private String funDescricao;

	@Column(name = "funSexo", nullable = false, length = 1)
	private char funSexo;

	public int getFunCod() {
		return this.funCod;
	}

	public void setFunCod(int funCod) {
		this.funCod = funCod;
	}

	public String getFunDescricao() {
		return this.funDescricao;
	}

	public void setFunDescricao(String funDescricao) {
		this.funDescricao = funDescricao;
	}

	public char getFunSexo() {
		return this.funSexo;
	}

	public void setFunSexo(char funSexo) {
		this.funSexo = funSexo;
	}

}
